[package]
distribution = "2201.2.0"
org = "ballerinax"
name = "aws.simpledb"
version = "2.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords= ["IT Operations/Databases", "Cost/Freemium", "Vendor/Amazon"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.simpledb"
icon = "icon.png"

[build-options]
observabilityIncluded = true